const Theme = {
    containerBg: '#000',
    cardBg: '#fff',
    tileGrey: '#333',
    sectionText: 'white',
    cardText: 'black',
    curve: 15,
    vSpacing: 15
 }

 const Moon = [
     'wi-moon-new',
     'wi-moon-waxing-crescent-1',
     'wi-moon-waxing-crescent-2',
     'wi-moon-waxing-crescent-3',
     'wi-moon-waxing-crescent-4',
     'wi-moon-waxing-crescent-5',
     'wi-moon-waxing-crescent-6',
     'wi-moon-first-quarter',
     'wi-moon-waxing-gibbous-1',
     'wi-moon-waxing-gibbous-2',
     'wi-moon-waxing-gibbous-3',
     'wi-moon-waxing-gibbous-4',
     'wi-moon-waxing-gibbous-5',
     'wi-moon-waxing-gibbous-6',
     'wi-full-moon',
     'wi-moon-waning-gibbous-1',
     'wi-moon-waning-gibbous-2',
     'wi-moon-waning-gibbous-3',
     'wi-moon-waning-gibbous-4',
     'wi-moon-waning-gibbous-5',
     'wi-moon-waning-gibbous-6',
     'wi-moon-third-quarter',
     'wi-moon-waning-crescent-1',
     'wi-moon-waning-crescent-2',
     'wi-moon-waning-crescent-3',
     'wi-moon-waning-crescent-4',
     'wi-moon-waning-crescent-5',
     'wi-moon-waning-crescent-6',
 ];

 const MoonPhase = [
    'New Moon',
    'Waxing Crescent',
    'Waxing Crescent',
    'Waxing Crescent',
    'Waxing Crescent',
    'Waxing Crescent',
    'Waxing Crescent',
    'First Quarter',
    'Waxing Gibbous',
    'Waxing Gibbous',
    'Waxing Gibbous',
    'Waxing Gibbous',
    'Waxing Gibbous',
    'Waxing Gibbous',
    'Full Moon',
    'Waning Gibbous',
    'Waning Gibbous',
    'Waning Gibbous',
    'Waning Gibbous',
    'Waning Gibbous',
    'Waning Gibbous',
    'Last Quarter',
    'Waning Crescent',
    'Waning Crescent',
    'Waning Crescent',
    'Waning Crescent',
    'Waning Crescent',
    'Waning Crescent',
]

 export { Theme, Moon, MoonPhase } ;